export default {
  CREATE_NEW_TODO_LIST_ITEM: "ADD_NEW_TODO_LIST_ITEM",
  UPDATE_TODO_LIST_ITEM_TEXT: "UPDATE_TODO_LIST_ITEM_TEXT",
  DELETE_TODO_LIST_ITEM: "DELETE_TODO_LIST_ITEM",
  TOGGLE_TODO_LIST_ITEM_DONE: "TOGGLE_TODO_LIST_ITEM_DONE",
};
